import { WearableProduct } from "../types";

export const PRODUCTS_DATA: WearableProduct[] = [
  {
    id: "garmin-fenix-8-solar",
    name: "Garmin Fenix 8 Solar (51mm)",
    brand: "Garmin",
    category: "Stamina & Endurance",
    wearableType: "Wrist",
    price: 999,
    originalPrice: 1099,
    rating: 4.9,
    reviewsCount: 342,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    ],
    batteryLife: "Up to 30 days (with solar)",
    batteryLifeDays: 30,
    staminaScore: 98,
    sleepScore: 92,
    recoveryScore: 96,
    waterResistance: "100m (10 ATM / Dive rated 40m)",
    connectivity: ["Multi-Band GNSS", "Bluetooth 5.3", "ANT+", "Wi-Fi"],
    compatibility: "Both",
    sensors: ["Elevate v5 Heart Rate", "ECG App", "Pulse Ox SpO2", "Barometric Altimeter", "Skin Temp", "Depth Gauge"],
    weightGrams: 95,
    subscriptionRequired: false,
    bestFor: ["⚡ Real-Time Stamina", "🏃 Ultra Running", "⛰️ Expedition", "🏊 Multisport"],
    primaryGoals: ["Stamina", "Running", "Fitness", "Recovery", "Heart Rate"],
    tagline: "The ultimate endurance multisport GPS smartwatch with Real-Time Stamina metrics.",
    description: "Built for extreme endurance athletes, the Fenix 8 Solar features Garmin's patented Real-Time Stamina engine that tracks and manages your exertion in real time to prevent premature burnout during marathons and climbs.",
    pros: [
      "Industry-leading Real-Time Stamina calculation & Training Readiness",
      "Immense battery life with solar sapphire lens",
      "Multi-band GPS with preloaded topographical trail maps",
      "Zero subscription fees for all advanced metrics"
    ],
    cons: [
      "Premium investment price point",
      "Heavier bulkier chassis for smaller wrists"
    ],
    specs: {
      display: "1.4\" Sunlight-visible transflective memory-in-pixel (MIP) Solar",
      dimensions: "51 x 51 x 15.4 mm",
      chargingTime: "1.5 hours",
      appEcosystem: "Garmin Connect & Connect IQ",
      warranty: "2 Years Limited",
      releaseYear: 2025
    },
    retailers: [
      {
        id: "deal-fenix-1",
        retailerName: "Garmin Direct",
        price: 999,
        originalPrice: 1099,
        currency: "$",
        couponCode: "STAMINA10",
        inStock: true,
        shippingText: "Free 2-Day Air",
        rating: 4.9,
        url: "https://www.garmin.com",
        isBestDeal: true
      },
      {
        id: "deal-fenix-2",
        retailerName: "REI Co-op",
        price: 999,
        originalPrice: 1099,
        currency: "$",
        inStock: true,
        shippingText: "Free Curbside Pickup or Shipping",
        rating: 4.8,
        url: "https://www.rei.com"
      },
      {
        id: "deal-fenix-3",
        retailerName: "Amazon",
        price: 1049,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free Next-Day",
        rating: 4.7,
        url: "https://www.amazon.com"
      }
    ],
    featured: true,
    trending: true,
    hasGps: true,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: true
  },
  {
    id: "oura-ring-gen-3-horizon",
    name: "Oura Ring Gen 3 Horizon",
    brand: "Oura",
    category: "Smart Ring",
    wearableType: "Finger",
    price: 299,
    originalPrice: 349,
    rating: 4.7,
    reviewsCount: 890,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    batteryLife: "Up to 7 days",
    batteryLifeDays: 7,
    staminaScore: 89,
    sleepScore: 98,
    recoveryScore: 97,
    waterResistance: "100m (Water-proof for swimming & diving)",
    connectivity: ["Bluetooth Low Energy (BLE)"],
    compatibility: "Both",
    sensors: ["Research-grade PPG sensors", "Negative Temperature Coefficient (NTC)", "3D Accelerometer", "Green/Red/Infrared LEDs"],
    weightGrams: 5,
    subscriptionRequired: true,
    subscriptionCost: "$5.99/mo (First month free)",
    bestFor: ["😴 Sleep Architecture", "🔋 Readiness Score", "🌡️ Daytime Stress & Temp", "✨ Screenless Minimalist"],
    primaryGoals: ["Sleep", "Recovery", "Stress", "Stamina", "General Health"],
    tagline: "The benchmark smart ring for deep sleep analysis, daily readiness, and illness detection.",
    description: "Slip on lightweight titanium comfort that measures blood pulse directly from your finger arteries—providing 10x higher signal accuracy for sleep stages, nighttime HRV, and temperature fluctuations.",
    pros: [
      "Ultra-comfortable 5g titanium design you forget you're wearing",
      "Gold standard sleep staging and daytime stress tracking",
      "Automatic nap and activity detection",
      "Water resistant to 100 meters"
    ],
    cons: [
      "Requires $5.99 monthly membership for full data insights",
      "No screen for real-time live pacing during runs"
    ],
    specs: {
      display: "Screenless (Titanium with PVD coating)",
      dimensions: "Width 7.9mm, Thickness 2.55mm",
      chargingTime: "45-80 minutes",
      appEcosystem: "Oura App (iOS / Android / Apple Health / Strava)",
      warranty: "1 Year Standard",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-oura-1",
        retailerName: "Best Buy",
        price: 299,
        originalPrice: 349,
        currency: "$",
        couponCode: "RING50",
        inStock: true,
        shippingText: "Free Next-Day Delivery",
        rating: 4.8,
        url: "https://www.bestbuy.com",
        isBestDeal: true
      },
      {
        id: "deal-oura-2",
        retailerName: "Oura Official Store",
        price: 299,
        originalPrice: 349,
        currency: "$",
        inStock: true,
        shippingText: "Free Sizing Kit Included",
        rating: 4.9,
        url: "https://ouraring.com"
      },
      {
        id: "deal-oura-3",
        retailerName: "Amazon",
        price: 319,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free Shipping",
        rating: 4.6,
        url: "https://www.amazon.com"
      }
    ],
    featured: true,
    trending: true,
    hasGps: false,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: false
  },
  {
    id: "whoop-4",
    name: "WHOOP 4.0 (with 12-Month Peak Membership)",
    brand: "WHOOP",
    category: "Recovery & Breathing",
    wearableType: "Wrist",
    price: 239,
    originalPrice: 289,
    rating: 4.6,
    reviewsCount: 650,
    image: "https://images.unsplash.com/photo-1576243345690-4e4b79b63288?auto=format&fit=crop&w=800&q=80",
    batteryLife: "4–5 days (Wireless on-wrist charging)",
    batteryLifeDays: 5,
    staminaScore: 94,
    sleepScore: 96,
    recoveryScore: 99,
    waterResistance: "IP68 / 10m Dust & Waterproof",
    connectivity: ["Bluetooth 5.0", "BLE Heart Rate Broadcast"],
    compatibility: "Both",
    sensors: ["5 LEDs (3 green, 1 red, 1 infrared)", "4 photodiodes", "Skin Conductance Sensor", "Skin Temp"],
    weightGrams: 27,
    subscriptionRequired: true,
    subscriptionCost: "Included in upfront membership package",
    bestFor: ["🔋 Strain vs Recovery", "🫁 HRV Diagnostics", "😴 Sleep Coach", "🏋️ Strength Trainer"],
    primaryGoals: ["Recovery", "Stamina", "Fitness", "Sleep", "Stress"],
    tagline: "The screen-free 24/7 physiological performance coach trusted by elite athletes.",
    description: "WHOOP continuously measures key vitals like Heart Rate Variability (HRV), resting heart rate, and skin temperature to provide daily Strain and Recovery scores, telling you precisely when to push your limits and when to rest.",
    pros: [
      "Elite recovery and strain modeling tailored to physiological capacity",
      "Slide-on wireless battery pack means you never take it off to charge",
      "Versatile wearability (wrist, bicep, WHOOP Body apparel)",
      "Strength Trainer feature tracks muscular strain and weight load"
    ],
    cons: [
      "Ongoing subscription model required to maintain access",
      "No onboard display or standalone GPS"
    ],
    specs: {
      display: "Screenless (Haptic motor notifications)",
      dimensions: "34 x 19 x 10 mm",
      chargingTime: "2 hours (via on-wrist battery pack)",
      appEcosystem: "WHOOP App (iOS / Android / TrainingPeaks / Apple Health)",
      warranty: "Lifetime with active membership",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-whoop-1",
        retailerName: "WHOOP Official",
        price: 239,
        originalPrice: 289,
        currency: "$",
        couponCode: "STAMINA15",
        inStock: true,
        shippingText: "Free Express Shipping",
        rating: 4.9,
        url: "https://www.whoop.com",
        isBestDeal: true
      },
      {
        id: "deal-whoop-2",
        retailerName: "Amazon",
        price: 249,
        originalPrice: 289,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free Shipping",
        rating: 4.5,
        url: "https://www.amazon.com"
      }
    ],
    featured: true,
    trending: true,
    hasGps: false,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: false
  },
  {
    id: "polar-h10-chest-strap",
    name: "Polar H10 Heart Rate Sensor",
    brand: "Polar",
    category: "Heart Rate Monitor",
    wearableType: "Chest",
    price: 89,
    originalPrice: 109,
    rating: 4.9,
    reviewsCount: 1420,
    image: "https://images.unsplash.com/photo-1510519138161-58474eb7d79c?auto=format&fit=crop&w=800&q=80",
    batteryLife: "400 hours (User-replaceable CR2025 coin cell)",
    batteryLifeDays: 90,
    staminaScore: 99,
    sleepScore: 40,
    recoveryScore: 95,
    waterResistance: "30m (Suitable for swimming & ECG data recording)",
    connectivity: ["Dual Bluetooth Low Energy", "ANT+", "5 kHz GymLink"],
    compatibility: "Both",
    sensors: ["Medical-grade Electrocardiogram (ECG) Electrodes", "Internal Memory for 1 session"],
    weightGrams: 60,
    subscriptionRequired: false,
    bestFor: ["❤️ Gold Standard HR Accuracy", "🏃 Interval Running / HIIT", "🚴 Zwift & Cycling", "💪 Orthostatic HRV Tests"],
    primaryGoals: ["Heart Rate", "Stamina", "Running", "Fitness"],
    tagline: "The undisputed scientific gold standard for ECG heart rate accuracy during high-intensity training.",
    description: "When optical wrist sensors falter during rapid heart rate spikes, the Polar H10 chest strap uses electrical chest conduction to deliver millisecond-exact pulse fidelity for intervals, CrossFit, and physiological threshold tests.",
    pros: [
      "Gold-standard ECG accuracy across all sports including swimming",
      "Dual simultaneous Bluetooth connections + ANT+",
      "Built-in memory to record a full training session without a phone",
      "Pro chest strap with silicone anti-slip dots"
    ],
    cons: [
      "Chest strap format is worn during workouts only (not 24/7 sleep)",
      "Coin cell replacement required once per year"
    ],
    specs: {
      display: "None (LED status indicator)",
      dimensions: "34 x 65 x 10 mm",
      chargingTime: "CR2025 Battery (Lasts ~400 training hours)",
      appEcosystem: "Polar Beat, Polar Flow, Strava, Garmin, Zwift, Apple Fitness+",
      warranty: "2 Years",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-polar-1",
        retailerName: "Amazon",
        price: 89,
        originalPrice: 109,
        currency: "$",
        couponCode: "SAVE20",
        inStock: true,
        shippingText: "Prime Free Next-Day",
        rating: 4.9,
        url: "https://www.amazon.com",
        isBestDeal: true
      },
      {
        id: "deal-polar-2",
        retailerName: "Polar Direct",
        price: 99,
        originalPrice: 109,
        currency: "$",
        inStock: true,
        shippingText: "Standard Free Shipping",
        rating: 4.8,
        url: "https://www.polar.com"
      },
      {
        id: "deal-polar-3",
        retailerName: "Backcountry",
        price: 94,
        originalPrice: 109,
        currency: "$",
        inStock: true,
        shippingText: "Free Shipping on $50+",
        rating: 4.8,
        url: "https://www.backcountry.com"
      }
    ],
    featured: true,
    trending: false,
    hasGps: false,
    hasSpO2: false,
    hasHrv: true,
    hasTemp: false,
    hasEcg: true
  },
  {
    id: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    category: "Smartwatch",
    wearableType: "Wrist",
    price: 749,
    originalPrice: 799,
    rating: 4.8,
    reviewsCount: 1120,
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80",
    batteryLife: "36–72 hours in Low Power Mode",
    batteryLifeDays: 3,
    staminaScore: 92,
    sleepScore: 94,
    recoveryScore: 91,
    waterResistance: "100m (EN13319 Recreational Dive to 40m)",
    connectivity: ["Dual-Frequency L1/L5 Precision GPS", "Cellular LTE", "Wi-Fi", "Bluetooth 5.3", "Ultra Wideband 2"],
    compatibility: "iPhone",
    sensors: ["Electrical Heart Sensor (ECG)", "Third-Gen Optical HR", "Dual Temp Sensors", "Depth Gauge & Water Temp", "Sirens & Action Button"],
    weightGrams: 61,
    subscriptionRequired: false,
    bestFor: ["⌚ Smart Ecosystem Integration", "🌊 Diving & Ocean Sports", "🏃 Running Power & HR Zones", "🧭 Outdoor Waypoints"],
    primaryGoals: ["Fitness", "Running", "General Health", "Heart Rate", "Stamina"],
    tagline: "Rugged aerospace-grade titanium smartwatch with the brightest display and deep cellular connectivity.",
    description: "Boasting a 3,000-nit edge-to-edge sapphire display, dual-frequency GPS, and customizable Action Button, the Ultra 2 bridges everyday communication with serious endurance tracking for iPhone users.",
    pros: [
      "Stunning 3000-nit ultra-bright display visible in direct glare",
      "Pristine dual-frequency GPS route mapping in dense urban canyons",
      "Seamless Apple Health and voice Siri integration",
      "Built-in 86dB emergency siren and dive computer capabilities"
    ],
    cons: [
      "iPhone only (Incompatible with Android devices)",
      "36-hour battery requires more frequent charging than dedicated endurance watches"
    ],
    specs: {
      display: "49mm Always-On Retina OLED (3,000 nits)",
      dimensions: "49 x 44 x 14.4 mm",
      chargingTime: "1 hour to 80%",
      appEcosystem: "watchOS & Apple Health ecosystem",
      warranty: "1 Year AppleCare eligible",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-ultra-1",
        retailerName: "Amazon",
        price: 749,
        originalPrice: 799,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free Next-Day",
        rating: 4.9,
        url: "https://www.amazon.com",
        isBestDeal: true
      },
      {
        id: "deal-ultra-2",
        retailerName: "Best Buy",
        price: 749,
        originalPrice: 799,
        currency: "$",
        inStock: true,
        shippingText: "Free Store Pickup Today",
        rating: 4.8,
        url: "https://www.bestbuy.com"
      },
      {
        id: "deal-ultra-3",
        retailerName: "Apple Store",
        price: 799,
        currency: "$",
        inStock: true,
        shippingText: "Free 2-Day Delivery",
        rating: 4.9,
        url: "https://www.apple.com"
      }
    ],
    featured: true,
    trending: true,
    hasGps: true,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: true
  },
  {
    id: "ringconn-gen-2",
    name: "RingConn Gen 2 Smart Ring",
    brand: "RingConn",
    category: "Smart Ring",
    wearableType: "Finger",
    price: 299,
    originalPrice: 329,
    rating: 4.8,
    reviewsCount: 420,
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80",
    batteryLife: "10–12 days per single charge",
    batteryLifeDays: 12,
    staminaScore: 91,
    sleepScore: 96,
    recoveryScore: 93,
    waterResistance: "IP68 & 100m Waterproof",
    connectivity: ["Bluetooth 5.2 Low Energy"],
    compatibility: "Both",
    sensors: ["4 Photoplethysmography (PPG) sensors", "Medical-grade Sleep Apnea Monitoring Algorithm", "3D Accelerometer", "Dual Temperature Sensors"],
    weightGrams: 3,
    subscriptionRequired: false,
    bestFor: ["🚫 Zero Subscription Fees", "🔋 12-Day Battery Life", "😴 Sleep Apnea Risk Detection", "✨ Featherlight (3g)"],
    primaryGoals: ["Sleep", "Recovery", "General Health", "Stress", "Stamina"],
    tagline: "The world's lightest smart ring with 12-day battery life, sleep apnea detection, and zero subscription.",
    description: "RingConn Gen 2 eliminates monthly subscription fees entirely while delivering class-leading 12-day battery life, breakthrough Sleep Apnea risk screening, and 24/7 continuous HRV monitoring in a 2mm slim titanium ring.",
    pros: [
      "No subscription fee ever — 100% features unlocked for life",
      "Unmatched 10–12 day battery endurance per charge",
      "Revolutionary Sleep Apnea detection feature with FDA submission",
      "Comes with a 500mAh portable charging case good for 150 days of power"
    ],
    cons: [
      "App UI is slightly less polished than Oura's narrative insights",
      "Fewer third-party app integrations currently"
    ],
    specs: {
      display: "Screenless (Titanium PVD ultra-thin)",
      dimensions: "Width 6.8mm, Thickness 2.0mm",
      chargingTime: "60 minutes",
      appEcosystem: "RingConn App (iOS / Android / Apple Health / Google Health Connect)",
      warranty: "1 Year Limited",
      releaseYear: 2025
    },
    retailers: [
      {
        id: "deal-ringconn-1",
        retailerName: "RingConn Official",
        price: 299,
        originalPrice: 329,
        currency: "$",
        couponCode: "SMARTSTAMINA",
        inStock: true,
        shippingText: "Free Global Express + Sizing Kit",
        rating: 4.9,
        url: "https://ringconn.com",
        isBestDeal: true
      },
      {
        id: "deal-ringconn-2",
        retailerName: "Amazon",
        price: 299,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free 2-Day",
        rating: 4.7,
        url: "https://www.amazon.com"
      }
    ],
    featured: true,
    trending: true,
    hasGps: false,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: false
  },
  {
    id: "coros-pace-3",
    name: "COROS Pace 3 GPS Sport Watch",
    brand: "COROS",
    category: "Fitness Band",
    wearableType: "Wrist",
    price: 229,
    originalPrice: 249,
    rating: 4.8,
    reviewsCount: 580,
    image: "https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=800&q=80",
    batteryLife: "17 days standard / 38 hours continuous GPS",
    batteryLifeDays: 17,
    staminaScore: 95,
    sleepScore: 86,
    recoveryScore: 92,
    waterResistance: "50m (5 ATM)",
    connectivity: ["Dual-Frequency All-Systems GNSS", "Bluetooth 5.0", "Wi-Fi"],
    compatibility: "Both",
    sensors: ["Optical HR Sensor (5 LEDs)", "Barometric Altimeter", "Pulse Ox SpO2", "Compass", "Thermometer"],
    weightGrams: 30,
    subscriptionRequired: false,
    bestFor: ["🏃 Best Value Running Watch", "🪶 Featherlight 30g", "🔋 Incredible GPS Battery", "📈 EvoLab Training Hub"],
    primaryGoals: ["Running", "Stamina", "Fitness", "Heart Rate"],
    tagline: "The champion lightweight running watch with dual-frequency GPS and free training analytics.",
    description: "At only 30 grams, the COROS Pace 3 is loved by competitive marathoners and track runners for its featherweight feel, pinpoint dual-frequency GPS accuracy, and COROS EvoLab training load metrics without recurring subscription costs.",
    pros: [
      "Incredible price-to-performance ratio for serious runners",
      "Only 30g with nylon band — barely noticeable on wrist",
      "38 hours of continuous GPS tracking",
      "Comprehensive training hub & marathon level predictions"
    ],
    cons: [
      "MIP display has lower contrast in dim lighting than AMOLED",
      "Basic smartwatch features (no NFC payments or voice calls)"
    ],
    specs: {
      display: "1.2\" Always-On Memory LCD touchscreen",
      dimensions: "41.9 x 41.9 x 11.7 mm",
      chargingTime: "less than 2 hours",
      appEcosystem: "COROS App, Strava, TrainingPeaks, Apple Health",
      warranty: "2 Years",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-coros-1",
        retailerName: "COROS Official",
        price: 229,
        originalPrice: 249,
        currency: "$",
        couponCode: "PACEFREE",
        inStock: true,
        shippingText: "Free Expedited Shipping",
        rating: 4.9,
        url: "https://coros.com",
        isBestDeal: true
      },
      {
        id: "deal-coros-2",
        retailerName: "Amazon",
        price: 229,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free Delivery",
        rating: 4.8,
        url: "https://www.amazon.com"
      },
      {
        id: "deal-coros-3",
        retailerName: "Running Warehouse",
        price: 229,
        currency: "$",
        inStock: true,
        shippingText: "Free 2-Day Air + 90-Day Returns",
        rating: 4.9,
        url: "https://www.runningwarehouse.com"
      }
    ],
    featured: true,
    trending: true,
    hasGps: true,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: false
  },
  {
    id: "ultrahuman-ring-air",
    name: "Ultrahuman Ring AIR",
    brand: "Ultrahuman",
    category: "Smart Ring",
    wearableType: "Finger",
    price: 349,
    originalPrice: 379,
    rating: 4.7,
    reviewsCount: 310,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    batteryLife: "Up to 6 days",
    batteryLifeDays: 6,
    staminaScore: 93,
    sleepScore: 95,
    recoveryScore: 96,
    waterResistance: "100m (Waterproof for scuba/swimming)",
    connectivity: ["Bluetooth 5.0 BLE"],
    compatibility: "Both",
    sensors: ["Fighter Jet Grade Titanium", "Infrared PPG Sensors", "Contact Skin Temp", "6-Axis Motion IMU"],
    weightGrams: 2.4,
    subscriptionRequired: false,
    bestFor: ["⚡ Circadian Rhythm Sync", "🚫 No Subscription", "🧪 Glucose / CGM Pairing", "🪶 Ultra Slim (2.4g)"],
    primaryGoals: ["Recovery", "Sleep", "Stamina", "General Health", "Stress"],
    tagline: "Featherlight titanium smart ring featuring circadian rhythm optimization and glucose biomarker pairing.",
    description: "Weighing only 2.4 grams with smooth medical epoxy inner lining, the Ultrahuman Ring AIR tracks sleep staging, temperature shifts, and circadian phase shifts with zero mandatory subscriptions.",
    pros: [
      "World's lightest smart ring chassis at 2.4 grams",
      "Dynamic Circadian Phase alignment algorithm for sleep & caffeine timing",
      "No subscription model for core biometric analysis",
      "Seamless synchronization with Ultrahuman M1 CGM continuous glucose monitors"
    ],
    cons: [
      "Battery life averages 5-6 days compared to RingConn's 12",
      "Occasional step count discrepancies during rough workouts"
    ],
    specs: {
      display: "Screenless (Titanium with Tungsten Carbide Carbon)",
      dimensions: "Width 8.1mm, Thickness 2.4mm",
      chargingTime: "90 minutes",
      appEcosystem: "Ultrahuman App, Apple Health, Google Fit",
      warranty: "1 Year Standard",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-uh-1",
        retailerName: "Ultrahuman Store",
        price: 349,
        originalPrice: 379,
        currency: "$",
        couponCode: "AIR10",
        inStock: true,
        shippingText: "Free Priority Worldwide",
        rating: 4.8,
        url: "https://www.ultrahuman.com",
        isBestDeal: true
      },
      {
        id: "deal-uh-2",
        retailerName: "Amazon",
        price: 359,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free Next-Day",
        rating: 4.6,
        url: "https://www.amazon.com"
      }
    ],
    featured: false,
    trending: true,
    hasGps: false,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: false
  },
  {
    id: "withings-scanwatch-2",
    name: "Withings ScanWatch 2 Clinical Hybrid",
    brand: "Withings",
    category: "Health Wearable",
    wearableType: "Wrist",
    price: 349,
    originalPrice: 399,
    rating: 4.6,
    reviewsCount: 290,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    batteryLife: "30 days per charge",
    batteryLifeDays: 30,
    staminaScore: 86,
    sleepScore: 93,
    recoveryScore: 88,
    waterResistance: "50m (5 ATM)",
    connectivity: ["Bluetooth Low Energy", "Connected GPS via Smartphone"],
    compatibility: "Both",
    sensors: ["Medical 1-Lead ECG", "TempTech24/7 Module", "Multi-wavelength PPG", "High Dynamic Range Altimeter"],
    weightGrams: 58,
    subscriptionRequired: false,
    bestFor: ["🩺 Clinical Health Baseline", "🔋 30-Day Battery", "👔 Classic Analog Luxury Look", "🌡️ 24/7 Body Temp Flux"],
    primaryGoals: ["General Health", "Heart Rate", "Sleep", "Recovery"],
    tagline: "Timeless luxury Swiss-style analog watch embedded with medical-grade ECG and 30-day battery life.",
    description: "ScanWatch 2 merges luxury stainless steel and sapphire glass watchmaking with clinical-grade health diagnostics: 30-second on-demand ECG for Afib detection, continuous body temperature fluctuation, and sleep breathing disturbance monitoring.",
    pros: [
      "Astonishing 30-day battery life in a timeless dress watch design",
      "On-demand medical-grade ECG reading certified for Afib detection",
      "TempTech24/7 continuous baseline temperature variance tracking",
      "Subtle, distraction-free OLED digital complication"
    ],
    cons: [
      "Relies on connected phone GPS (no built-in GNSS)",
      "Minimalist display is not meant for real-time complex map navigation"
    ],
    specs: {
      display: "Analog hands + 0.63\" PMOLED sub-display",
      dimensions: "38mm or 42mm casing, 13.2mm thickness",
      chargingTime: "2 hours",
      appEcosystem: "Withings App (Apple Health / Google Fit / Strava)",
      warranty: "2 Years",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-scan-1",
        retailerName: "Withings Official",
        price: 349,
        originalPrice: 399,
        currency: "$",
        couponCode: "HEALTH50",
        inStock: true,
        shippingText: "Free Ground Shipping",
        rating: 4.8,
        url: "https://www.withings.com",
        isBestDeal: true
      },
      {
        id: "deal-scan-2",
        retailerName: "Best Buy",
        price: 349,
        originalPrice: 399,
        currency: "$",
        inStock: true,
        shippingText: "Free 2-Day Shipping",
        rating: 4.7,
        url: "https://www.bestbuy.com"
      }
    ],
    featured: false,
    trending: false,
    hasGps: false,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: true,
    hasEcg: true
  },
  {
    id: "garmin-edge-840-solar",
    name: "Garmin Edge 840 Solar Cycling Computer",
    brand: "Garmin",
    category: "Cycling Computer",
    wearableType: "Clip-on",
    price: 549,
    originalPrice: 599,
    rating: 4.9,
    reviewsCount: 230,
    image: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
    batteryLife: "32–60 hours in Battery Saver Mode",
    batteryLifeDays: 3,
    staminaScore: 99,
    sleepScore: 0,
    recoveryScore: 94,
    waterResistance: "IPX7 Waterproof",
    connectivity: ["Multi-Band GNSS", "ANT+", "BLE", "Wi-Fi"],
    compatibility: "Both",
    sensors: ["Barometric Altimeter", "Ambient Light Sensor", "ClimbPro 2.0", "Cycling Ability / Power Curve"],
    weightGrams: 85,
    subscriptionRequired: false,
    bestFor: ["🚴 Road & Gravel Cycling", "⚡ Real-Time Stamina While Riding", "⛰️ ClimbPro Ascent Management", "☀️ Solar Power Glass"],
    primaryGoals: ["Cycling", "Stamina", "Fitness"],
    tagline: "Solar-powered touchscreen & button cycling computer with dynamic Real-Time Stamina coaching.",
    description: "Engineered specifically for cyclists who need to pace steep alpine climbs and 100-mile gran fondos, Edge 840 Solar calculates live aerobic and anaerobic stamina depletion in real-time right on your handlebars.",
    pros: [
      "Real-time Stamina gauge tells you how much energy you have left in the tank",
      "Power Guide recommends target wattages across specific course segments",
      "ClimbPro works on any route without preloaded courses",
      "Both responsive touchscreen and tactile physical buttons for rain/gloves"
    ],
    cons: [
      "Bike-mounted only (not worn on body 24/7)",
      "Best paired with external power meters and heart rate straps"
    ],
    specs: {
      display: "2.6\" Color Touchscreen Solar Display",
      dimensions: "57.8 x 85.1 x 19.6 mm",
      chargingTime: "2 hours",
      appEcosystem: "Garmin Connect, Strava, Komoot, TrainingPeaks",
      warranty: "2 Years",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-edge-1",
        retailerName: "Garmin Direct",
        price: 549,
        originalPrice: 599,
        currency: "$",
        inStock: true,
        shippingText: "Free 2-Day Air",
        rating: 4.9,
        url: "https://www.garmin.com",
        isBestDeal: true
      },
      {
        id: "deal-edge-2",
        retailerName: "Competitive Cyclist",
        price: 549,
        currency: "$",
        inStock: true,
        shippingText: "Free Guaranteed 2-Day",
        rating: 4.8,
        url: "https://www.competitivecyclist.com"
      }
    ],
    featured: false,
    trending: false,
    hasGps: true,
    hasSpO2: false,
    hasHrv: true,
    hasTemp: true,
    hasEcg: false
  },
  {
    id: "apollo-neuro-band",
    name: "Apollo Neuro Stress Relief Wearable",
    brand: "Apollo Neuro",
    category: "Stress & Wellbeing",
    wearableType: "Wrist",
    price: 299,
    originalPrice: 349,
    rating: 4.5,
    reviewsCount: 380,
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    batteryLife: "6–8 hours of active vibration therapy",
    batteryLifeDays: 1,
    staminaScore: 84,
    sleepScore: 92,
    recoveryScore: 95,
    waterResistance: "Water-resistant splashproof",
    connectivity: ["Bluetooth Low Energy"],
    compatibility: "Both",
    sensors: ["Sub-sensory Acoustic Haptic Transducer", "Heart Rate Sync Algorithm", "SmartVibes AI"],
    weightGrams: 35,
    subscriptionRequired: false,
    bestFor: ["🧠 Nervous System Regulation", "🧘 Active Stress Reduction", "😴 Falling Asleep Faster", "⚡ Energy & Focus Boost"],
    primaryGoals: ["Stress", "Recovery", "Sleep", "Wellbeing"],
    tagline: "Neuroscience-backed wearable delivering gentle soothing vibrations to balance your autonomic nervous system.",
    description: "Unlike passive trackers, Apollo actively improves your HRV and stamina by sending scientifically calibrated silent vibration frequencies (Apollo Vibes) that stimulate your touch receptors and shift your nervous system from fight-or-flight to rest-and-digest.",
    pros: [
      "Active intervention tool that directly lowers cortisol and boosts HRV",
      "SmartVibes AI automatically senses nighttime awakenings and soothes you back to sleep",
      "Can be worn on wrist, ankle, or clipped to clothing",
      "Clinically shown to increase deep sleep by up to 19%"
    ],
    cons: [
      "Requires frequent nightly recharging",
      "Does not display step counts or workout mile splits"
    ],
    specs: {
      display: "Screenless (Two tactile control buttons)",
      dimensions: "49 x 35 x 15 mm",
      chargingTime: "2 hours (micro-USB magnetic)",
      appEcosystem: "Apollo Neuro App (iOS / Android / Oura Ring integration)",
      warranty: "1 Year Standard",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-apollo-1",
        retailerName: "Apollo Neuro Direct",
        price: 299,
        originalPrice: 349,
        currency: "$",
        couponCode: "CALM50",
        inStock: true,
        shippingText: "Free US Shipping + 30-Day Money Back",
        rating: 4.9,
        url: "https://apolloneuro.com",
        isBestDeal: true
      },
      {
        id: "deal-apollo-2",
        retailerName: "Amazon",
        price: 329,
        originalPrice: 349,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free 2-Day",
        rating: 4.4,
        url: "https://www.amazon.com"
      }
    ],
    featured: false,
    trending: true,
    hasGps: false,
    hasSpO2: false,
    hasHrv: true,
    hasTemp: false,
    hasEcg: false
  },
  {
    id: "withings-sleep-tracking-pad",
    name: "Withings Sleep Tracking Pad",
    brand: "Withings",
    category: "Sleep Tracker",
    wearableType: "Under-Mattress",
    price: 129,
    originalPrice: 149,
    rating: 4.7,
    reviewsCount: 520,
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
    batteryLife: "Continuous Wall Plug-in Power (Zero Battery Hassle)",
    batteryLifeDays: 365,
    staminaScore: 82,
    sleepScore: 99,
    recoveryScore: 91,
    waterResistance: "Non-submersible (Fabric cover washable)",
    connectivity: ["Wi-Fi 2.4GHz", "Bluetooth 4.0 Setup"],
    compatibility: "Both",
    sensors: ["Pneumatic Ballistocardiography Sensor", "Sound Sensor for Snoring", "Continuous Heart Rate & HRV Detection"],
    weightGrams: 260,
    subscriptionRequired: false,
    bestFor: ["🛏️ Zero-Wear Sleep Tracking", "🔌 Never Needs Recharging", "😴 Snoring & Sleep Apnea Analysis", "🏡 Smart Home Home Automation"],
    primaryGoals: ["Sleep", "Recovery", "General Health"],
    tagline: "Slip-under-mattress mat that delivers lab-grade sleep analysis without wearing anything on your body.",
    description: "For people who hate wearing watches or rings to bed, the Withings Sleep Pad fits invisibly under any mattress. Using pneumatic sensors, it tracks heart rate, breathing cycles, sleep stages, and snoring frequency continuously.",
    pros: [
      "100% effortless — completely zero wearables on your body in bed",
      "No battery charging needed (plugs into standard wall outlet)",
      "High-precision sleep cycle, snoring, and breathing disturbance analysis",
      "IFTTT and smart home integration (e.g. dim lights when you get into bed)"
    ],
    cons: [
      "Tracks sleep at home only (not portable for travel hotel beds)",
      "Does not track daytime activity, steps, or athletic workouts"
    ],
    specs: {
      display: "Invisible under-mattress placement",
      dimensions: "637 x 190 x 5 mm",
      chargingTime: "Continuous 110-240V AC power supply",
      appEcosystem: "Withings App (Apple Health / Google Fit)",
      warranty: "2 Years",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-sleep-pad-1",
        retailerName: "Amazon",
        price: 129,
        originalPrice: 149,
        currency: "$",
        couponCode: "SLEEP20",
        inStock: true,
        shippingText: "Prime Free Next-Day",
        rating: 4.8,
        url: "https://www.amazon.com",
        isBestDeal: true
      },
      {
        id: "deal-sleep-pad-2",
        retailerName: "Best Buy",
        price: 129,
        originalPrice: 149,
        currency: "$",
        inStock: true,
        shippingText: "Free Delivery",
        rating: 4.7,
        url: "https://www.bestbuy.com"
      }
    ],
    featured: false,
    trending: false,
    hasGps: false,
    hasSpO2: true,
    hasHrv: true,
    hasTemp: false,
    hasEcg: false
  },
  {
    id: "stryd-next-gen-footpod",
    name: "Stryd Next Gen Running Power Footpod",
    brand: "Stryd",
    category: "Fitness Sensor",
    wearableType: "Shoe/Foot",
    price: 249,
    originalPrice: 279,
    rating: 4.9,
    reviewsCount: 390,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    batteryLife: "1 month per charge (~20 hours running)",
    batteryLifeDays: 30,
    staminaScore: 98,
    sleepScore: 0,
    recoveryScore: 90,
    waterResistance: "IP67 Splash and Puddle Proof",
    connectivity: ["Dual Bluetooth Low Energy", "ANT+"],
    compatibility: "Both",
    sensors: ["6-Axis Accelerometers & Gyroscopes", "Wind Tunnel Sensor", "Impact Shock & Leg Spring Stiffness"],
    weightGrams: 8,
    subscriptionRequired: false,
    bestFor: ["⚡ Running Power (Watts)", "🏃 Marathon Pacing Precision", "🌬️ Real-Time Wind & Air Resistance", "👟 Shoe Clip (8g)"],
    primaryGoals: ["Running", "Stamina", "Fitness"],
    tagline: "The running power meter that gives athletes a single metric for endurance pacing on hills and headwinds.",
    description: "Clips securely to your shoe laces to calculate real running power (in Watts) accounting for elevation changes and headwind drag, enabling flawless negative splits and stamina conservation during half and full marathons.",
    pros: [
      "Unrivaled running power accuracy that eliminates uphill guesswork",
      "Accounts for environmental wind and air resistance live",
      "Instant pace and distance without relying on satellite GPS drift",
      "Compatible with Garmin, Apple Watch, COROS, Polar, and Suunto"
    ],
    cons: [
      "Running-specific tool only",
      "Requires clipping onto shoe laces before workouts"
    ],
    specs: {
      display: "Screenless (Shoe clip)",
      dimensions: "40 x 30 x 10 mm",
      chargingTime: "1 hour via magnetic cradle",
      appEcosystem: "Stryd Mobile App, Garmin Connect, TrainingPeaks, Final Surge",
      warranty: "1 Year",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-stryd-1",
        retailerName: "Stryd Official",
        price: 249,
        originalPrice: 279,
        currency: "$",
        couponCode: "POWERSTAMINA",
        inStock: true,
        shippingText: "Free Worldwide Express",
        rating: 4.9,
        url: "https://www.stryd.com",
        isBestDeal: true
      },
      {
        id: "deal-stryd-2",
        retailerName: "Running Warehouse",
        price: 249,
        currency: "$",
        inStock: true,
        shippingText: "Free 2-Day Shipping",
        rating: 4.8,
        url: "https://www.runningwarehouse.com"
      }
    ],
    featured: false,
    trending: false,
    hasGps: false,
    hasSpO2: false,
    hasHrv: false,
    hasTemp: false,
    hasEcg: false
  },
  {
    id: "garmin-hrm-pro-plus",
    name: "Garmin HRM-Pro Plus Premium Chest Strap",
    brand: "Garmin",
    category: "Heart Rate Monitor",
    wearableType: "Chest",
    price: 129,
    originalPrice: 149,
    rating: 4.8,
    reviewsCount: 710,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80",
    batteryLife: "1 year (1 hour/day training, tool-free battery door)",
    batteryLifeDays: 365,
    staminaScore: 97,
    sleepScore: 0,
    recoveryScore: 94,
    waterResistance: "50m (5 ATM / Swimming HR support)",
    connectivity: ["ANT+", "Multiple Bluetooth Low Energy"],
    compatibility: "Both",
    sensors: ["Running Dynamics (Cadence, Vertical Oscillation, Ground Contact Time, Stride Length)", "Internal Pace & Distance"],
    weightGrams: 52,
    subscriptionRequired: false,
    bestFor: ["🏃 Advanced Running Dynamics", "❤️ Studio & Treadmill Pace", "🏊 Swimming Heart Rate Store & Forward", "💪 Indoor HIIT"],
    primaryGoals: ["Heart Rate", "Running", "Stamina", "Fitness"],
    tagline: "Chest strap capturing ECG-level heart rate along with advanced biomechanical running dynamics.",
    description: "Captures accurate heart rate data plus advanced running dynamics (ground contact balance, vertical ratio, stride length) and transmits live to your smartwatch, smart trainer, or treadmill without a GPS lock.",
    pros: [
      "Measures running power, cadence, and ground contact time balance",
      "Stores heart rate during team sports or swimming and syncs later",
      "Quarter-turn tool-free battery door makes CR2032 swap effortless",
      "Transmits simultaneous ANT+ and dual BLE channels"
    ],
    cons: [
      "Works best within the Garmin Connect ecosystem for running dynamics",
      "Not designed for 24/7 casual sleep tracking"
    ],
    specs: {
      display: "None",
      dimensions: "Strap width 30mm, module thickness 12mm",
      chargingTime: "CR2032 Coin Cell (Lasts ~12 months)",
      appEcosystem: "Garmin Connect, Strava, Zwift, Tacx",
      warranty: "1 Year Standard",
      releaseYear: 2024
    },
    retailers: [
      {
        id: "deal-hrm-1",
        retailerName: "Amazon",
        price: 129,
        originalPrice: 149,
        currency: "$",
        inStock: true,
        shippingText: "Prime Free One-Day",
        rating: 4.8,
        url: "https://www.amazon.com",
        isBestDeal: true
      },
      {
        id: "deal-hrm-2",
        retailerName: "Garmin Direct",
        price: 139,
        originalPrice: 149,
        currency: "$",
        inStock: true,
        shippingText: "Free Standard Delivery",
        rating: 4.9,
        url: "https://www.garmin.com"
      }
    ],
    featured: false,
    trending: false,
    hasGps: false,
    hasSpO2: false,
    hasHrv: true,
    hasTemp: false,
    hasEcg: true
  }
];
